spring:
  #application:
   # name: product-microservice
  #mvc:
   # view:
     # prefix: /WEB-INF/views/
     # suffix: .jsp
    #static-path-pattern: /resources/**
      
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
# Discovery Server Access
#eureka:
  #client:
    #  serviceUrl:
      #  defaultZone: http://localhost:1112/eureka/

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
server:
  error:
    whitelabel:
      enabled: false
  port: 9591
#spring.profiles.active=dev
# JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)

#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.database=default
#spring.jpa.show-sql=true
# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#spring.datasource.continue-on-error=false
#spring.datasource.generate-unique-name=false

#spring.h2.console.settings.web-allow-others=true

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  