### Spring properties
# Service registers under this name
spring:
  application:
    name: student-microservice

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1112/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 3333

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
  error:
    whitelabel:
      enabled: false

